-- AlterTable: added in three steps rather than one NOT NULL DEFAULT, because
-- cuid() is generated by Prisma in the client and Postgres has no such
-- function to backfill existing rows with.
ALTER TABLE "Delivery" ADD COLUMN     "publicToken" TEXT;
UPDATE "Delivery" SET "publicToken" = gen_random_uuid()::text WHERE "publicToken" IS NULL;
ALTER TABLE "Delivery" ALTER COLUMN "publicToken" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "Delivery_publicToken_key" ON "Delivery"("publicToken");
